// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ems.Models;

#nullable disable

namespace ems.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20230310092851_TaskBase Create")]
    partial class TaskBaseCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ems.Models.TaskBase", b =>
                {
                    b.Property<string>("Task")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeadLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Task");

                    b.ToTable("TaskBase");
                });
#pragma warning restore 612, 618
        }
    }
}
